services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./:/app
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./:/app
    # mysql:
    #     image: mariadb:latest
    #     environment:
    #         MYSQL_ROOT_PASSWORD: 'secret123'
    #         MYSQL_USER: 'developer'
    #         MYSQL_PASSWORD: 'secret123'
    #         MYSQL_DATABASE: 'pscdb'
    #     volumes:
    #         - mysqldata:/var/lib/mysql
    #         - ./sql:/docker-entrypoint-initdb.d
    #     ports:
    #         - 3306:3306
    # phpmyadmin:
    #     image: phpmyadmin:latest
    #     ports:
    #         - 8080:80
    #     environment:
    #         - PMA_HOST=mysql
    #         - PMA_USER=root
    #         - PMA_PASSWORD=secret123
volumes:
    mysqldata: {}
