services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./vue:/app/frontend
            - ./php:/app/backend
        depends_on:
            - php
            - frontend
        networks:
            - app-network

    php:
        build:
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - ./php:/app/backend
        networks:
            - app-network

    frontend:
        build:
            context: ./vue
            dockerfile: Dockerfile
        volumes:
            - ./vue:/app/frontend
            - frontend-pnpm:/app/frontend/node_modules/.pnpm
            - /app/frontend/node_modules
        environment:
            - NODE_ENV=development
        networks:
            - app-network

    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret123'
            MYSQL_USER: 'developer'
            MYSQL_PASSWORD: 'secret123'
            MYSQL_DATABASE: 'demodb'
        volumes:
            - mysqldata:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        networks:
            - app-network
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8081:80
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=secret123
        networks:
            - app-network
volumes:
    frontend-pnpm:
    mysqldata:
networks:
    app-network:
        driver: bridge
